
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml?placeholder-type=environment
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 100
          max-wait: 5000


logging:
  level:
    org.springframework.security: trace
    com.atlas.common.core.api: info

security:
  domain: localhost
  issuerUrl: http://localhost:9090
  uiUrl: http://localhost:3000
  webauthn:
    rpId: localhost
    rpName: Atlas Identity Server
    origins:
      - http://localhost:9090
      - http://localhost:3000

atlas:
  user:
    server-url: http://localhost:9091
  auth:
    server-url: http://localhost:9096
  file:
    server-url: http://localhost:9097
  notification:
    server-url: http://localhost:9099