
spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 100
          max-wait: 5000
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # 用户服务
            - id: user_route
              uri: http://localhost:9091
              predicates:
                - Path=/api/user/** # 匹配以此路径开头的请求
              filters:
                - StripPrefix=2 # 转发前剥离 2 层路径

            # 认证服务
            - id: auth_route
              uri: http://localhost:9096
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            # 文件服务
            - id: file_route
              uri: http://localhost:9097
              predicates:
                - Path=/api/file/**
              filters:
                - StripPrefix=2
            - id: file_access_route
              uri: http://localhost:9097
              predicates:
                - Path=/file/**

            # 消息通知服务
            - id: notification_route
              uri: http://localhost:9099
              predicates:
                - Path=/api/notification/**
              filters:
                - StripPrefix=2


rate-limit:
  services:
    - serviceId: auth-service
      uri: http://localhost:9096
      stripPrefix: 2
      limits:
        - path: /api/auth/code/send-email
          capacity: 1 # 令牌桶容量（或最大访问次数） 在指定周期内同一个 Key 最多允许访问 1 次
          periodInSeconds: 60 # 限流周期 配合 capacity 使用
          methods: ["POST"]
          keyResolverName: ipKeyResolver