server:
  port: 9097
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: file-service
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    async:
      request-timeout: -1
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  cloud:
    circuitbreaker:
      resilience4j:
        disable-thread-pool: false
  config:
    import:
      - classpath:config/resilience4j.yaml


logging:
  level:
    com.atlas.common.core.api: info

mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

http:
  config:
    # 连接池中允许存在的最大 HTTP 连接总数（整个 JVM 进程共享）
    maxConnTotal: 500
    # 单个目标主机（同一域名 + 端口）的最大并发连接数
    maxConnPerRoute: 100
    # 从连接池中获取连接的最大等待时间 单位：秒
    connectionRequestTimeout: 5
    # 建立连接后，等待服务端返回数据的最大时间（Socket 超时） 单位：秒
    responseTimeout: 60
    # 是否跳过 HTTPS 证书校验（仅限 dev/test，生产必须为 false）
    insecureSkipVerify: true
    # HTTP 代理地址
    proxy:

atlas:
  user:
    server-url: http://user-service
  auth:
    server-url: http://auth-service
  file:
    server-url: http://file-service
  notification:
    server-url: http://notification-service

file:
  access-url: https://atlas.ys0921.sbs:4443
  avatar:
    base-url: http://ys0921.sbs:43000/10.x
    default-type: avataaars
    default-format: svg

management:
  endpoint:
    health:
      probes:
        enabled: true # 显式开启 Liveness 和 Readiness 探针
      show-details: always # 方便排查具体哪个组件挂了
  endpoints:
    web:
      exposure:
        include: health