
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml?placeholder-type=environment
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 100
          max-wait: 5000


redisson:
  config:
    single-server-config:
      database: 0
      password: ${REDIS_PASSWORD:}
      address: "redis://${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6379}"