
worker_processes  auto;

events {
    worker_connections  2048;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # --- 性能优化：基础传输 ---
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on; # 提高实时性
    keepalive_timeout  65;

    # --- 性能优化：核心 Gzip 压缩 ---
    # 开启后，前端 js/css 体积通常能缩小 60%~80%
    gzip  on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_vary on;

    server {
        listen       80;
        server_name  atlas-docs.ys0921.sbs;

        root   /usr/share/nginx/html;

        index  index.html index.htm;
        
        # 基于相对路径重定向
        absolute_redirect off;

        location / {
            try_files $uri $uri/ /index.html;
            
            # html 禁止缓存
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        # --- 2. 静态资源强缓存 ---
        # 配合 Vite/Webpack 生成的带哈希的文件名，极大提升后续访问速度
        location ~* \.(?:js|css|jpg|jpeg|gif|png|ico|svg|woff|woff2)$ {
            root /usr/share/nginx/html;
            expires 7d;
            add_header Cache-Control "public, no-transform";
            access_log off; # 减少 IO，不记录静态资源日志
        }

        # 错误页面配置
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}